### ISSUE TITLE
Tutorial 

### ISSUE THREAD

**Issue by nixfreak** [ThomasTJdev/nim_tutorials#1]
/.env/nim/nimweb/main.nim(36, 1) template/generic instantiation of `settings` from here
.env/nim/nimweb/main.nim(37, 14) Error: type mismatch: got <string> but expected 'Port = distinct uint16'

Are you on a chat or IRC , would it be better communication then here ? 
Let me know if I'm bothering you on such trivial matter also.

**Comment by ThomasTJdev** [comment]
Hi @nixfreak 

It's fine. Just keep asking. I prefer to keep it here at Github for now.

I have just checked the code visually, and it should work. Can you provide me with info:
```
Nim version
Jester version
Httpbeast version
OS (linux, mac, windows)
```

Can you copy paste the full error message into a code-tag here on Github using 3 backticks \`\`\`?

**Comment by nixfreak** [comment]
Nim Version: Nim Compiler Version 1.0.4 [MacOSX: amd64]
Compiled at 2019-11-27

Jester:
 jester  [0.4.3]

Httpbeast:
httpbeast  [0.2.2]

OS/Kernel:
 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64

```.env/nim/nimweb/code/password_utils.nim(1, 21) Warning: imported and not used: 'math' [UnusedImport]
.env/nim/nimweb/code/password_utils.nim(1, 35) Warning: imported and not used: 'os' [UnusedImport]
.env/nim/nimweb/code/database_utils.nim(1, 33) Warning: imported and not used: 'strutils' [UnusedImport]
.env/nim/nimweb/code/database_utils.nim(1, 43) Warning: imported and not used: 'logging' [UnusedImport]
.env/nim/nimweb/code/database_utils.nim(3, 15) Warning: imported and not used: 'password_utils' [UnusedImport]
.env/nim/nimweb/main.nim(36, 1) template/generic instantiation of `settings` from here
.env/nim/nimweb/main.nim(37, 14) Error: type mismatch: got <string> but expected 'Port = distinct uint16' 
```

``` # Jester setting server settings
settings:
  port = Port(mainPort)
  bindAddr = mainURL 
```

**Comment by nixfreak** [comment]
```hello```

**Comment by ThomasTJdev** [comment]
I've just tested it locally with the same versions of jester, httpbeast and Nim, and it works out of the box. I'm running Linux, so I can't test on Mac.

But let's try to debug.

Jester is initializing the webserver settings through:
```
settings:
  port = Port(mainPort)
  bindAddr = mainURL 
```
Here we are using `mainPort` to hold the port, which is gathered from the `config.cfg` file:
```
let mainPort  = parseInt dict.getSectionValue("Server", "port")
```
We are reading the `config.cfg` file with the `dict.getSectionValue` and we are transforming it into an integer with `parseInt`.

Your error code indicates, that the `mainPort` Jester is using is in a wrong format. It is getting a `string` instead of a `integer (uint16)`. This indicates, that the error is with our `parseInt` - which I have absolutely no explanation for!

To debug or fix it you should first check what type `mainPort` actually is. Do this with:
```
let mainURL   = dict.getSectionValue("Server", "url")
let mainPort  = parseInt dict.getSectionValue("Server", "port")
echo mainPort.type # This should print "int"
let mainWebsite = dict.getSectionValue("Server", "website")
```
If `echo mainPort.type` does not print `int`, try to wrap it like this:
```
let mainURL   = dict.getSectionValue("Server", "url")
let mainPort  = parseInt(dict.getSectionValue("Server", "port")) # See the () ?
echo mainPort.type # This should print "int"
let mainWebsite = dict.getSectionValue("Server", "website")
```
If the error message actually wants 'uint`, then change to this:
```
let mainURL   = dict.getSectionValue("Server", "url")
let mainPort  = parseUInt(dict.getSectionValue("Server", "port")) 
echo mainPort.type # This should print "uint"
let mainWebsite = dict.getSectionValue("Server", "website")
```

**Comment by ThomasTJdev** [comment]
Well, I just looked at your code output - it shows that logging, strutils, etc. is imported but not used. That can't be right! Are you using the code from: https://github.com/ThomasTJdev/nim_tutorials/tree/master/code/nimweb ?

Your output shows:
```
.env/nim/nimweb/code/database_utils.nim(1, 43) Warning: imported and not used: 'logging' [UnusedImport]
```
But `database_utils.nim` uses `logging` on line 82, 95 and 97.

**Comment by nixfreak** [comment]
I created a repo and uploaded all code https://github.com/nixfreak/nimweb

**Comment by ThomasTJdev** [comment]
> I created a repo and uploaded all code https://github.com/nixfreak/nimweb

You line 27 in main.nim is wrong. You are not parsing the port. 
```
let mainPort = dict.getSectionValue("Server", "port")
```

You are reading the port as a `string`, you need to transform it to an `integer`. Change to this:
```
let mainPort = parseInt(dict.getSectionValue("Server", "port"))
```

**Comment by nixfreak** [comment]
Thank you, I wrote it all out to actually learn , thanks again for letting me ask you questions.

**Comment by ThomasTJdev** [comment]
No problem. I think that was a good way to learn Nim. Just ask, if you have any other questions.
